export const categories = [
    'Automotive - Helmets & Riding Gloves',
    'Automotive - Tyres & Rims',
    'Automotive Vehicles - 2-Wheelers 4-Wheelers and Electric Vehicles',
    'Automotive – Car and Bike parts',
    'Automotive – Cleaning kits',
    'Automotive Accessories',
    'Vehicle Tools and Appliances',
    'Oils Lubricants',
    'Automotive – Batteries and air fresheners',
    'Car Electronics Devices',
    'Car Electronics Accessories',
    'Baby Hardlines',
    'Baby Strollers',
    'Baby diapers',
    'Books',
    'Movies',
    'Music',
    'Musical Instruments - Guitars',
    'Musical Instruments - Keyboards',
    'Musical Instruments - Microphones',
    'Musical Instruments - Others',
    'Video Games - Online game services',
    'Video Games - Accessories',
    'Video Games - Consoles',
    'Video Games',
    'Business and Industrial Supplies - Scientific Supplies',
    'OTC Medicine',
    'Masks',
    'Weighing Scales & Fat Analyzers',
    '3D Printers',
    'Business and Industrial Supplies - Material Handling Equipment',
    'Business and Industrial Supplies - Electrical Testing',
    'Business and Industrial Supplies - Power tools & accessories',
    'Occupational Safety Supplies',
    'Stethoscopes',
    'Packing materials',
    'Power & hand Tools and Water Dispenser',
    'Office products - Office supplies',
    'Office products - Electronic Devices',
    'Office products - Arts and Crafts',
    'Office products - Writing Instruments',
    'Apparel - Accessories',
    'Apparel - Sweat Shirts and Jackets',
    'Apparel - Shorts',
    'Apparel - Baby',
    'Apparel - Ethnic wear',
    'Apparel - Other innerwear',
    'Apparel - Sleepwear',
    'Apparel - Sarees and Dress Materials',
    'Apparel - Men\'s T-shirts',
    'Apparel - Womens\' Innerwear / Lingerie',
    'Backpacks',
    'Eyewear',
    'Fashion Jewellery',
    'Fine Jewellery - Gold Coins',
    'Fine Jewellery - studded',
    'Fine Jewellery - unstudded and solitaire',
    'Silver Jewellery',
    'Flip Flops Fashion Sandals and Slippers',
    'Handbags',
    'Luggage - Suitcase & Trolleys',
    'Luggage - Travel Accessories',
    'Kids shoes',
    'Shoes',
    'Shoes - Sandals & Floaters',
    'Wallets',
    'Watches',
    'Cables and Adapters',
    'Camera Accessories',
    'Camera Lenses',
    'Camera and Camcorder',
    'Cases Covers Skins Screen Guards',
    'Desktops',
    'Electronic Accessories',
    'Electronic Devices',
    'Entertainment Collectibles',
    'Fashion Smartwatches',
    'GPS Devices',
    'Hard Disks',
    'Headsets Headphones and Earphones',
    'Keyboards and Mouse',
    'Kindle Accessories',
    'Laptop Bags & Sleeves',
    'Laptop and Camera Battery',
    'Laptops',
    'Memory Cards',
    'Mobile phones',
    'Tablets',
    'Modems & Networking Devices',
    'Monitors',
    'PC Components',
    'Power Banks & Chargers',
    'Printers & Scanners',
    'Software Products',
    'Speakers',
    'Television',
    'Landline Phones',
    'Smart Watches & Accessories',
    'USB Flash Drives',
    'Projectors Home Theatre Systems',
    'Grocery - herbs and spices',
    'Grocery & Gourmet - Oils',
    'Grocery - Dried fruits and nuts',
    'Grocery - Hampers and gifting',
    'Pet food',
    'Pet Products',
    'Beauty - Fragrance',
    'Beauty - Haircare Bath and Shower',
    'Beauty - Makeup',
    'Face Wash',
    'Moisturizer cream',
    'Sunscreen',
    'Deodrants',
    'Facial steamers',
    'Prescription Medicine',
    'Health & Personal Care - Medical Equipment & Contact Lens',
    'Health and Personal Care - Ayurvedic products',
    'Health & Household - Sports Nutrition',
    'Health and Personal Care - Contact lens',
    'Health and Household - Household Cleaning',
    'Health and Household - Vitamins & Supplements',
    'Luxury Beauty',
    'Car Cradles Lens Kits and Tablet Cases',
    'Personal Care Appliances - Electric Massagers',
    'Personal Care Appliances - Grooming & Styling',
    'Personal Care Appliances - Glucometer',
    'Personal Care Appliances - Thermometers',
    'Bean Bags & Inflatables',
    'Mattresses',
    'Rugs and Doormats',
    'Clocks',
    'Wall Art',
    'Home - Fragrance & Candles',
    'Bedsheets Blankets and covers',
    'Home furnishing',
    'Containers Boxes Bottles Kitchen Storage',
    'Home improvement - Accessories',
    'Home improvement (excl. accessories)',
    'Tiles & Flooring Accessories',
    'Wires',
    'Ladders Kitchen and Bath fixtures',
    'Home Storage',
    'Wallpapers & Wallpaper Accessories',
    'Home Decor Products',
    'Wall Paints and Tools',
    'Home - Waste & Recycling',
    'Craft materials',
    'Water Purifier and Accessories',
    'Water Heaters and Accessories',
    'Home improvement - Kitchen & Bath',
    'Sanitaryware',
    'Home Safety & Security Systems',
    'Inverter and Batteries',
    'Cleaning and Home Appliances',
    'Indoor Lighting',
    'Doors and Windows',
    'LED Bulbs and Battens',
    'Cushion Covers',
    'Curtains and Curtain Accessories',
    'Slipcovers and Kitchen Linens',
    'Safes and Lockers',
    'Lawn & Garden - Solar Panels',
    'Lawn & Garden - Leaf blower',
    'Lawn & Garden - Commercial Agricultural',
    'Lawn & Garden - Chemical Pest Control',
    'Lawn & Garden - Solar Devices',
    'Lawn and Garden - Planters',
    'Lawn and Garden - Plants Seeds & Bulbs',
    'Lawn & Garden - Outdoor equipments',
    'Kitchen - Non Appliances',
    'Kitchen - Glassware & Ceramicware',
    'Kitchen - Gas Stoves & Pressure Cookers',
    'Large Appliances (excl. specified)',
    'Large Appliances - Accessories',
    'Large Appliances - Chimneys',
    'Large Appliances - Refrigerators',
    'Small Appliances',
    'Fans and Robotic Vacuums',
    'Bicycles',
    'Sports & Outdoors - Footwear',
    'Coin Collectibles',
    'Silver Coins & Bars',
    'Furniture - Other products',
    'Consumable Physical Gift Card',
    'Warranty Services'
  ] as const;
  